In [180]:
%matplotlib notebook
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [209]:
import matplotlib.pyplot as plt
import numpy as np
import recov.datasets

from recov.util import quat_to_rot_matrix

In [182]:
d = recov.datasets.HuskyDataset('/home/dlandry/dataset/husky/2018-05-30-small/')

In [183]:
d.odometry_estimate(18,13)

array([[ 0.78092348,  0.62719891,  0.04327989,  8.3895406 ],
       [-0.62470042,  0.77440009,  0.09817614, -5.02247278],
       [ 0.03270786,  0.08131387,  0.99342959,  0.88950501],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [184]:
t = d.odometry_estimate(18,13)
r = t[0:3,0:3]

In [185]:
np.linalg.eig(r)

(array([0.77554707+0.61913496j, 0.77554707-0.61913496j,
        0.99765904+0.j        ]),
 array([[ 0.70642193+0.j        ,  0.70642193-0.j        ,
          0.15974073+0.j        ],
        [-0.01093739+0.70153349j, -0.01093739-0.70153349j,
         -0.01291295+0.j        ],
        [ 0.07074652-0.06077935j,  0.07074652+0.06077935j,
          0.98707454+0.j        ]]))

In [186]:
t_17 = d.scan_pose[17]
t_map_12 = d.map_pose[12]

In [187]:
t_map_12

array([[ 0.99495298,  0.09809167, -0.02113284, -0.25666371],
       [-0.09781063,  0.99517009,  0.00591142,  0.17300233],
       [ 0.02161063,  0.00591142,  0.9997592 , -0.51408559],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [188]:
np.dot(t_map_12, t_map_12.T)

array([[ 1.06587626, -0.04422743,  0.13290079, -0.25666371],
       [-0.04422743,  1.02989517, -0.07925889,  0.17300233],
       [ 0.13290079, -0.07925889,  1.26430442, -0.51408559],
       [-0.25666371,  0.17300233, -0.51408559,  1.        ]])

In [189]:
r = t_map_12[0:3,0:3]

In [190]:
np.dot(r,r.T)

array([[1.00000000e+00, 1.75984868e-04, 9.53672085e-04],
       [1.75984868e-04, 9.99965368e-01, 9.67911869e-03],
       [9.53672085e-04, 9.67911869e-03, 1.00002042e+00]])

# Are the quaternions normalized in the csvs

In [191]:
import csv

In [192]:
with open('/home/dlandry/.ros/maps.csv') as f:
    reader = csv.DictReader(f)
    rows = [row for row in reader]

In [193]:
rows

[{'filename': 'map_00000.pcd',
  'qw': '1.00000000000000000',
  'qx': '0.00000000000000000',
  'qy': '0.00000000000000000',
  'qz': '0.00000000000000000',
  'timestamp': '1526925648.62882304191589355',
  'tx': '0.00000000000000000',
  'ty': '0.00000000000000000',
  'tz': '0.00000000000000000'},
 {'filename': 'map_00001.pcd',
  'qw': '0.99999975413080999',
  'qx': '-0.00033130830849093',
  'qy': '-0.00029385003966877',
  'qz': '-0.00052741846464434',
  'timestamp': '1526925648.72894001007080078',
  'tx': '-0.02343379584530934',
  'ty': '-0.00442818675537434',
  'tz': '-0.02516536872242726'},
 {'filename': 'map_00002.pcd',
  'qw': '0.99999641626431135',
  'qx': '-0.00020443302268133',
  'qy': '-0.00120735694274105',
  'qz': '-0.00240261619471357',
  'timestamp': '1526925649.02919793128967285',
  'tx': '-0.01471888340165362',
  'ty': '0.00491406182521888',
  'tz': '-0.10941901406395552'},
 {'filename': 'map_00003.pcd',
  'qw': '0.99996081662897263',
  'qx': '0.00006875199507047',
  'qy': 

In [214]:
rows[-1]
q = np.array([float(rows[3]['qx']), float(rows[3]['qy']),float(rows[3]['qz']),float(rows[3]['qw'])])

In [215]:
q

array([ 6.87519951e-05, -2.02507544e-03, -8.62144328e-03,  9.99960817e-01])

In [216]:
np.linalg.norm(q)

1.0000000348674138

In [217]:
q2 = np.array([-0.0303887698,-0.0088147263,0.0719795466,0.9969040917])


In [218]:
np.linalg.norm(q2)

0.9999999999533224

In [219]:
q2 = q2 / np.linalg.norm(q2)

In [220]:
np.linalg.norm(q2)

1.0

In [221]:
r = quat_to_rot_matrix({'i':q[0], 'j':q[1], 'k':q[2], 'w':q[3]})

In [222]:
np.dot(r, r.T)

array([[ 1.00000000e+00,  8.47898624e-06, -4.74148257e-06],
       [ 8.47898624e-06,  9.99999708e-01, -2.74921967e-04],
       [-4.74148257e-06, -2.74921967e-04,  9.99999981e-01]])

In [178]:
scan_p = d.scan_pose[17]
map_p = d.map_pose[12]

In [179]:
np.dot(map_p[0:3,0:3], map_p[0:3,0:3].T)

array([[1.00000000e+00, 1.75984868e-04, 9.53672085e-04],
       [1.75984868e-04, 9.99965368e-01, 9.67911869e-03],
       [9.53672085e-04, 9.67911869e-03, 1.00002042e+00]])

# New index format

In [235]:
with open('/home/dlandry/.ros/scans.csv') as f:
    reader = csv.DictReader(f)
    maps = [row for row in reader]

In [236]:
maps[25]

{'filename': 'scan_00025.pcd',
 'r00': '0.70117172938886441',
 'r01': '0.71237098786149089',
 'r02': '0.02976208257283944',
 'r10': '-0.71282330918872805',
 'r11': '0.69948529073683785',
 'r12': '0.05102213166883858',
 'r20': '0.01552854735833323',
 'r21': '-0.05699038248726547',
 'r22': '0.99825395592549249',
 'timestamp': '1526925675.85257911682128906',
 'tx': '12.75449193797631331',
 'ty': '-10.76979423990540496',
 'tz': '0.46251222654468072'}

In [241]:
len(maps)

31

In [244]:
m = maps[30]
r = np.zeros((3,3))

for i in range(0,3):
    for j in range(0,3):
        r[i,j] = m['r{}{}'.format(i,j)]

In [245]:
r

array([[ 0.71898624,  0.69314414,  0.05108811],
       [-0.69500277,  0.71644039,  0.06069853],
       [ 0.00547125, -0.07914779,  0.99684788]])

In [246]:
np.dot(r,r.T)

array([[ 1.00000000e+00,  6.43248871e-17, -5.94597348e-18],
       [ 6.43248871e-17,  1.00000000e+00, -6.25854365e-20],
       [-5.94597348e-18, -6.25854365e-20,  1.00000000e+00]])