In [2]:
import numpy as np
from lieroy import se3

In [9]:
mean = np.array([[1.0, 0.0, 0.0, 2.0],
                [0.0, 1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0, 0.0],
                [0.0, 0.0, 0.0, 1.0]])

sample = se3.sample_uniform(mean=mean, n_samples=100)

lie_vectors = np.empty((6, len(sample)))
for i, t in enumerate(sample):
    lie_vectors[:, i] = se3.log(t)

In [10]:
lie_vectors

array([[ 1.51638854e+00,  1.46259522e+00,  2.46093893e+00,
         2.55422091e+00,  2.00879931e+00,  1.82725704e+00,
         1.91041851e+00,  2.34825420e+00,  1.41517651e+00,
         1.90504730e+00,  1.97180057e+00,  1.47470140e+00,
         2.74499774e+00,  1.73896337e+00,  1.10749590e+00,
         1.47082806e+00,  1.36674583e+00,  2.05689049e+00,
         1.70766950e+00,  1.29122317e+00,  2.17941976e+00,
         2.77953959e+00,  2.24842215e+00,  2.15110087e+00,
         1.19600868e+00,  2.82977653e+00,  1.34052825e+00,
         1.23177254e+00,  1.63900650e+00,  2.17278671e+00,
         1.76869357e+00,  2.79503250e+00,  9.47665274e-01,
         2.20582676e+00,  2.03672814e+00,  2.34478498e+00,
         2.76626039e+00,  2.30914855e+00,  1.70775390e+00,
         1.49019158e+00,  2.13423800e+00,  1.75042379e+00,
         1.79501987e+00,  1.01489282e+00,  1.16872382e+00,
         1.88894081e+00,  1.50856447e+00,  2.40485525e+00,
         1.90504074e+00,  2.02194810e+00,  2.35099792e+0

In [11]:
lie_vectors.mean(axis=1)

array([ 1.85906092,  0.021257  ,  0.01281024, -0.04059176,  0.00690643,
       -0.02346967])

In [12]:
adj_inv_mean = se3.adjoint(np.linalg.inv(mean))

In [13]:
adj_inv_mean

array([[ 1.,  0.,  0.,  0., -0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  1., -0., -2.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [14]:
transformed = np.dot(adj_inv_mean, lie_vectors)

In [16]:

transformed.mean(axis=1)

array([ 1.85906092e+00, -2.56823357e-02, -1.00261589e-03, -4.05917585e-02,
        6.90643021e-03, -2.34696654e-02])

In [ ]:
sample[0]